### PR TITLE
[enhancement]: adding key to iterator over the knobs

### PR DESCRIPTION
**Pull request by hetpatel33**
Issue: https://github.com/Raathigesh/retoggle/issues/9

### CODE REVIEW

**Comment by Raathigesh** [comment]
Thank for you the PR. Please feel free to add yourself as a contributor to the readme as well :)

**Comment by hetpatel33** [comment]
> Thank for you the PR. Please feel free to add yourself as a contributor to the readme as well :)

@Raathigesh, How to add me as a contributor, can you pass me the guidelines for the same?

**Comment by hetpatel33** [comment]
@Raathigesh, Do I need to add it manually or is there any way to auto-generate it, as manual editing is not giving proper CSS.

**Comment by Raathigesh** [comment]
There is a CLI to automate it I guess. But I never used it before but that's something probably i should look into. [An example markup with multiple contributors if that helps.](https://raw.githubusercontent.com/Raathigesh/majestic/next/README.md)

**Comment by hetpatel33** [comment]
> There is a CLI to automate it I guess. But I never used it before but that's something probably i should look into. [An example markup with multiple contributors if that helps.](https://raw.githubusercontent.com/Raathigesh/majestic/next/README.md)

@Raathigesh, Raised a PR for the same. Please approve.

**Pull request merged**
