### PR TITLE
allow passing in custom state handler

### PR DESCRIPTION
**Pull request by ammmze**
Looks like I need a little enhancement to my previous changes. As i'm trying to integrate this into a react-styleguidist project it turns out there are basically 2 react tree's it uses. There's an outer one that renders the pages, then an inner one that is created via a `ReactDOM.mount` to mount the code example block. So in my scenario I need to be able to pass the context value from the outer tree and pass it into the inner tree. So I need to have the ability to pass in a custom context value or have access to the `InspectorContext` created from `React.createContext`. I've made both possible here.

### CODE REVIEW

**Comment by Raathigesh** [comment]
New version published with this change.

**Comment by ammmze** [comment]
👍  thank you ... appreciate it

**Comment by ammmze** [comment]
Hmm...looks like something got goofed up with the release? I pulled in 1.1.0, but it doesn't look like it has the changes.

**Comment by Raathigesh** [comment]
I think I did mess up the release. I'll push another one tonight. Sorry about that.

**Comment by ammmze** [comment]
No worries 👍

**Comment by Raathigesh** [comment]
I thought I didn't pull the newly merged changes before publishing the package but it looks like I did pull the changes. So I'm not quite sure why you are not seeing the changes :(

**Comment by ammmze** [comment]
Just to confirm it wasn't something local I created a codesandbox pulling it in and yea its still not there.

https://codesandbox.io/s/jovial-haibt-v3t43?file=/src/App.js

**Comment by ammmze** [comment]
@Raathigesh if I had to guess, it looks like what is published was the state at commit c4eecd3. In that commit the version was updated to `1.1.0`. But that was done directly from the `1.0.0` tag. And I had noticed that the README was updated on master after the `1.0.0` tag to remove contributors list. And the version published on NPM still has the contributor list. Here's a visual to try to better show what appears to have happened.

retoggle* 2020-06-29 11-38-20

Any chance you can bump to 1.1.1 and publish again?

**Comment by Raathigesh** [comment]
Thanks for that. I did publish 1.1.1 now. Please check and let me know if that fixes the problem.

**Comment by ammmze** [comment]
👍 That looks better 😀 Thank you ... appreciate it!

**Pull request merged**
